# Generated by Django 6.0.2 on 2026-02-07 07:35

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kontaktseite',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('body', wagtail.fields.StreamField([('hero', 9), ('features', 18), ('cta', 21), ('faq', 26), ('pricing', 36), ('team', 41), ('stats', 44), ('richtext', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Badge-Text über dem Titel', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide Icon Name (z.B. 'unlock')", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hauptüberschrift', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Unterüberschrift', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text für primären Button', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL für primären Button', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text für sekundären Button', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL für sekundären Button', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Indigo)'), ('green', 'Grün'), ('amber', 'Amber'), ('blue', 'Blau'), ('rose', 'Rose')], 'help_text': 'Hintergrund-Gradient'}), 9: ('wagtail.blocks.StructBlock', [[('badge_text', 0), ('badge_icon', 1), ('title', 2), ('subtitle', 3), ('primary_cta_text', 4), ('primary_cta_url', 5), ('secondary_cta_text', 6), ('secondary_cta_url', 7), ('gradient_from', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Abschnitts-Überschrift', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide Icon Name', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icon', 12), ('title', 13), ('description', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten'), ('4', '4 Spalten')]}), 18: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 11), ('features', 16), ('columns', 17)]], {}), 19: ('wagtail.blocks.URLBlock', (), {'required': True}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('dark', 'Dunkel'), ('gradient', 'Gradient')]}), 21: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 11), ('button_text', 13), ('button_url', 19), ('style', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Häufig gestellte Fragen', 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('question', 13), ('answer', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 22), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Transparente Preise', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': "z.B. '0€', '49€/Monat'", 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('no', 'Normal'), ('yes', 'Hervorgehoben')]}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Kontakt aufnehmen', 'required': False}), 33: ('wagtail.blocks.URLBlock', (), {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('name', 13), ('price', 28), ('description', 11), ('features', 30), ('is_highlighted', 31), ('cta_text', 32), ('cta_url', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {}), 36: ('wagtail.blocks.StructBlock', [[('title', 27), ('subtitle', 11), ('tiers', 35)]], {}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Das Team', 'required': False}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('name', 13), ('role', 13), ('image', 38), ('bio', 11)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('title', 37), ('members', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Mandari in Zahlen', 'required': False}), 43: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('yes', 'Ja'), ('no', 'Nein')], 'help_text': 'Kommunen-Statistik anzeigen'}), 44: ('wagtail.blocks.StructBlock', [[('title', 42), ('show_bodies', 43)]], {}), 45: ('wagtail.blocks.CharBlock', (), {'required': False}), 46: ('wagtail.blocks.StructBlock', [[('title', 45), ('body', 23)]], {})})),
            ],
            options={
                'verbose_name': 'Startseite',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField()),
                ('custom_template', models.CharField(blank=True, help_text="Optionaler Template-Pfad (z.B. 'marketing/impressum.html'). Leer = Standard-Template.", max_length=100)),
            ],
            options={
                'verbose_name': 'Rechtliche Seite',
                'verbose_name_plural': 'Rechtliche Seiten',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MarketingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 9), ('features', 18), ('cta', 21), ('faq', 26), ('pricing', 36), ('team', 41), ('stats', 44), ('richtext', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Badge-Text über dem Titel', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Lucide Icon Name (z.B. 'unlock')", 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hauptüberschrift', 'required': True}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'Unterüberschrift', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text für primären Button', 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL für primären Button', 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Text für sekundären Button', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'URL für sekundären Button', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary (Indigo)'), ('green', 'Grün'), ('amber', 'Amber'), ('blue', 'Blau'), ('rose', 'Rose')], 'help_text': 'Hintergrund-Gradient'}), 9: ('wagtail.blocks.StructBlock', [[('badge_text', 0), ('badge_icon', 1), ('title', 2), ('subtitle', 3), ('primary_cta_text', 4), ('primary_cta_url', 5), ('secondary_cta_text', 6), ('secondary_cta_url', 7), ('gradient_from', 8)]], {}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Abschnitts-Überschrift', 'required': False}), 11: ('wagtail.blocks.TextBlock', (), {'required': False}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Lucide Icon Name', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'required': True}), 14: ('wagtail.blocks.TextBlock', (), {'required': True}), 15: ('wagtail.blocks.StructBlock', [[('icon', 12), ('title', 13), ('description', 14)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2 Spalten'), ('3', '3 Spalten'), ('4', '4 Spalten')]}), 18: ('wagtail.blocks.StructBlock', [[('title', 10), ('subtitle', 11), ('features', 16), ('columns', 17)]], {}), 19: ('wagtail.blocks.URLBlock', (), {'required': True}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('dark', 'Dunkel'), ('gradient', 'Gradient')]}), 21: ('wagtail.blocks.StructBlock', [[('title', 13), ('description', 11), ('button_text', 13), ('button_url', 19), ('style', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'default': 'Häufig gestellte Fragen', 'required': False}), 23: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 24: ('wagtail.blocks.StructBlock', [[('question', 13), ('answer', 23)]], {}), 25: ('wagtail.blocks.ListBlock', (24,), {}), 26: ('wagtail.blocks.StructBlock', [[('title', 22), ('items', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'Transparente Preise', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': "z.B. '0€', '49€/Monat'", 'required': True}), 29: ('wagtail.blocks.CharBlock', (), {}), 30: ('wagtail.blocks.ListBlock', (29,), {}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('no', 'Normal'), ('yes', 'Hervorgehoben')]}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'Kontakt aufnehmen', 'required': False}), 33: ('wagtail.blocks.URLBlock', (), {'required': False}), 34: ('wagtail.blocks.StructBlock', [[('name', 13), ('price', 28), ('description', 11), ('features', 30), ('is_highlighted', 31), ('cta_text', 32), ('cta_url', 33)]], {}), 35: ('wagtail.blocks.ListBlock', (34,), {}), 36: ('wagtail.blocks.StructBlock', [[('title', 27), ('subtitle', 11), ('tiers', 35)]], {}), 37: ('wagtail.blocks.CharBlock', (), {'default': 'Das Team', 'required': False}), 38: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('name', 13), ('role', 13), ('image', 38), ('bio', 11)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {}), 41: ('wagtail.blocks.StructBlock', [[('title', 37), ('members', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Mandari in Zahlen', 'required': False}), 43: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('yes', 'Ja'), ('no', 'Nein')], 'help_text': 'Kommunen-Statistik anzeigen'}), 44: ('wagtail.blocks.StructBlock', [[('title', 42), ('show_bodies', 43)]], {}), 45: ('wagtail.blocks.CharBlock', (), {'required': False}), 46: ('wagtail.blocks.StructBlock', [[('title', 45), ('body', 23)]], {})})),
                ('custom_template', models.CharField(blank=True, help_text="Optionaler Template-Pfad (z.B. 'marketing/produkt.html'). Leer = Standard-Template.", max_length=100)),
            ],
            options={
                'verbose_name': 'Marketing-Seite',
                'verbose_name_plural': 'Marketing-Seiten',
            },
            bases=('wagtailcore.page',),
        ),
    ]
