# Generated by Django 6.1.1 on 2026-10-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            (
                                "vorgruendung",
                                "Vorgründung (Rechtsträger: topixmedia, Inhaber Sven Konopka)",
                            ),
                            ("gesellschaft", "Gesellschaft (Angaben unten)"),
                        ],
                        default="vorgruendung",
                        help_text="Bestimmt, welcher Rechtsträger auf /unternehmen/ und /kontakt/ erscheint. Impressum, Datenschutz, AGB und AVV schalten nicht automatisch um.",
                        max_length=20,
                        verbose_name="Stufe",
                    ),
                ),
                (
                    "announce_founding",
                    models.BooleanField(
                        default=True,
                        help_text="Nur in der Vorgründung: kurzer Hinweis unter den Angaben zum Unternehmen.",
                        verbose_name="Hinweis auf die geplante Gesellschaft zeigen",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        default="mandari UG (haftungsbeschränkt)",
                        max_length=200,
                        verbose_name="Firma",
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        default="Unternehmergesellschaft (haftungsbeschränkt)",
                        max_length=200,
                        verbose_name="Rechtsform",
                    ),
                ),
                (
                    "managing_directors",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Geschäftsführung"
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Straße und Hausnummer"
                    ),
                ),
                (
                    "postal_city",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="PLZ und Ort"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=50, verbose_name="Telefon"),
                ),
                (
                    "register_court",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Amtsgericht Münster",
                        max_length=200,
                        verbose_name="Registergericht",
                    ),
                ),
                (
                    "register_number",
                    models.CharField(
                        blank=True,
                        help_text="z. B. HRB 00000",
                        max_length=50,
                        verbose_name="Registernummer",
                    ),
                ),
                (
                    "vat_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Umsatzsteuer-Identifikationsnummer",
                    ),
                ),
                (
                    "founded",
                    models.CharField(
                        blank=True,
                        help_text="z. B. 2026",
                        max_length=50,
                        verbose_name="Gründung",
                    ),
                ),
                (
                    "liability_insurance",
                    models.CharField(
                        blank=True,
                        help_text="z. B. Betriebs- und Vermögensschadenhaftpflicht, Deckungssumme auf Anfrage",
                        max_length=255,
                        verbose_name="Haftpflicht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unternehmensangaben",
            },
        ),
    ]
